// import { FaUserCog } from 'react-icons/fa';

export const formFieldconfig = {
  "/users/role": {
    Category: "User & Role",
    title: "Role",
    formLabel: "Define access levels for user roles",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "Role Name",
        key: "typeName",
        type: "input",
        required: true,
        placeholder: "e.g., Admin, Super Admin",
      },
      {
        label: "Description",
        key: "description",
        type: "input",
        required: true,
        placeholder: "Description",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "Role",
    hasClearButton: true,
    submitUrl: "/api/v1/user-type",
  },

  "/users": {
    Category: "User & Role",
    title: "User",
    formLabel: "Define access levels for user",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "User Name",
        key: "userName",
        type: "input",
        required: true,
        placeholder: "Username",
      },
      {
        label: "Email",
        key: "userEmail",
        type: "input",
        required: true,
        placeholder: "Email",
      },
      {
        label: "Password",
        key: "passwordHash",
        type: "password",
        required: true,
        placeholder: "Password",
      },
      {
        label: "Role",
        key: "userTypeId",
        type: "select",
        required: true,
        placeholder: "Role",
        getListUrl: "/api/v1/user-type",
        valueKey: "userTypeId",
        optionKey: "typeName",
      },
      {
        label: "Status",
        key: "isActive",
        type: "select",
        required: true,
        placeholder: "Status",
        defaultList: [
          { value: true, option: "Active" },
          { value: false, option: "Invative" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Country",
        key: "countryID",
        type: "select",
        required: true,
        placeholder: "Country",
        valueKey: "countryId",
        optionKey: "countryName",
        getListUrl: "/api/v1/common/countries",
      },
      {
        label: "Mobile",
        key: "mobile",
        type: "number",
        required: true,
        placeholder: "Mobile",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "User",
    hasClearButton: true,
    submitUrl: "/api/v1/user",
  },

  "/users/update": {
    Category: "User & Role",
    title: "User",
    formLabel: "Define access levels for user",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "User Name",
        key: "userName",
        type: "input",
        required: true,
        placeholder: "Username",
      },
      {
        label: "Email",
        key: "userEmail",
        type: "input",
        required: true,
        placeholder: "Email",
      },
      {
        label: "Role",
        key: "userTypeId",
        type: "select",
        required: true,
        placeholder: "Role",
        getListUrl: "/api/v1/user-type",
        valueKey: "userTypeId",
        optionKey: "typeName",
      },
      {
        label: "Status",
        key: "isActive",
        type: "select",
        required: true,
        placeholder: "Status",
        defaultList: [
          { value: true, option: "Active" },
          { value: false, option: "Invative" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Country",
        key: "countryID",
        type: "select",
        required: true,
        placeholder: "Country",
        valueKey: "countryId",
        optionKey: "countryName",
        getListUrl: "/api/v1/common/countries",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "User",
    hasClearButton: true,
    submitUrl: "/api/v1/user",
  },

  "/products": {
    Category: "Products",
    title: "Product",
    formLabel: "",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "Product Name",
        key: "name",
        type: "input",
        required: true,
        placeholder: "Product Name",
      },
      {
        label: "Product Code",
        key: "pcode",
        type: "input",
        required: true,
        placeholder: "Product Code",
        isExistCheck: true,
      },
      {
        label: "Product Type",
        key: "productTypeID",
        type: "select",
        required: true,
        defaultList: [
          { value: 1, option: "Licensed" },
          { value: 2, option: "Subscription" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Status",
        key: "isActive",
        type: "select",
        required: true,
        placeholder: "Status",
        defaultList: [
          { value: true, option: "Active" },
          { value: false, option: "Invative" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Description",
        key: "description",
        type: "textArea",
        required: true,
        placeholder: "Description",
        class: "w-32",
      },
      {
        label: "Is Common",
        key: "iscommon",
        type: "checkbox",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "Product",
    hasClearButton: true,
    submitUrl: "/api/v1/product",
  },
  "/products/plan": {
    Category: "Product Plans",
    title: "Plan",
    formLabel: "",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "Plan Name",
        key: "planName",
        type: "input",
        required: true,
        placeholder: "Plan Name",
      },
      {
        label: "Currency",
        key: "currencyID",
        type: "select",
        required: true,
        // defaultList: [
        //   { value: "8D5C3D62-DCED-4756-8367-04927829E39B", option: "SAR" },
        // ],
        valueKey: "currencyID",
        optionKey: "currencyCode",
        getListUrl: "/api/v1/common/Currency"
      },
      {
        label: "Plan Price Was",
        key: "planPriceWas",
        type: "number",
        required: true,
        placeholder: "Plan Price",
      },
      {
        label: "Plan Price Now",
        key: "planPrice",
        type: "number",
        required: true,
        placeholder: "Plan Price",
      },
      {
        label: "Billing Cycle",
        key: "billingCycle",
        type: "select",
        required: true,
        defaultList: [
          { value: "Monthly", option: "Monthly" },
          // { value: "3", option: "Quarterly" },
          // { value: "6", option: "Semi-Annually" },
          { value: "Yearly", option: "Yearly" },
          // { value: "24", option: "Biennially" },
          // { value: "36", option: "Triennially" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Status",
        key: "isActive",
        type: "select",
        required: true,
        defaultList: [
          { value: true, option: "Active" },
          { value: false, option: "Inactive" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Plan Unique Code",
        key: "code",
        type: "input",
        required: true,
        placeholder: "Plan Unique Code",
        isExistCheck: true,
      },
      {
        key: "features",
        type: "features",
      },
      {
        label: "Description",
        key: "description",
        type: "textArea",
        required: true,
        placeholder: "Description",
        class: "w-32",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "Plan",
    hasClearButton: true,
    submitUrl: "/api/v1/product-plan",
  },

  "/products/version": {
    Category: "Product Version",
    title: "Version",
    formLabel: "",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "Version Number",
        key: "versionNumber",
        type: "input",
        required: true,
        placeholder: "Version Number",
      },
      {
        label: "Release Date",
        key: "releaseDate",
        type: "dateTime",
        required: true,
      },
      {
        label: "Version Price",
        key: "basePrice",
        type: "number",
        required: true,
        placeholder: "Version Price",
      },
      {
        label: "Currency",
        key: "currencyID",
        type: "select",
        required: true,
        // defaultList: [
        //   { value: "8358cf62-245a-33b9-dafa-e275cc1a5318", option: "SAR" },
        // ],
        valueKey: "currencyID",
        optionKey: "currencyCode",
        getListUrl: "/api/v1/common/Currency",
      },
      {
        label: "Country Name",
        key: "countryName",
        type: "select",
        required: true,
        valueKey: "countryId",
        optionKey: "countryName",
        getListUrl: "/api/v1/common/countries",
      },
      {
        type: "plan-selector",
        key: "planIDs",
      },
      {
        type: "dragable-adons",
        key: "addonIDs"
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "Version",
    hasClearButton: true,
    submitUrl: "/api/v1/product-version",
  },

  "/products/editions": {
    Category: "Product Edition",
    title: "Edition",
    formLabel: "",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "Edition Name",
        key: "eName",
        type: "input",
        required: true,
        placeholder: "Edition Name",
      },
      {
        label: "Edition Code",
        key: "eCode",
        type: "input",
        required: true,
        placeholder: "Edition Code",
        isExistCheck: true,
      },
      {
        label: "Number Of Users",
        key: "noOfUsers",
        type: "number",
        required: true,
        placeholder: "Number Of Users",
      },
      {
        label: "Status",
        key: "isActive",
        type: "select",
        required: true,
        placeholder: "Status",
        defaultList: [
          { value: true, option: "Active" },
          { value: false, option: "Invative" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Monthly Price",
        key: "monthlyPrice",
        type: "number",
        required: true,
        placeholder: "Monthly Price",
      },
      {
        label: "Yearly Price",
        key: "yearlyPrice",
        type: "number",
        required: true,
        placeholder: "Yearly Price",
      },
      {
        label: "Description",
        key: "description",
        type: "textArea",
        required: true,
        placeholder: "Description",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "Edition",
    hasClearButton: true,
    submitUrl: "/api/v1/edition",
  },

  "/products/addons": {
    Category: "Add-ons",
    title: "Add-ons",
    formLabel: "",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "Add-ons Name",
        key: "name",
        type: "input",
        required: true,
        placeholder: "Add-ons Name",
      },
      {
        label: "Add-ons price",
        key: "addonPrice",
        type: "number",
        required: true,
        placeholder: "Add-ons price",
      },
      {
        label: "Currency",
        key: "currencyID",
        type: "select",
        required: true,
        valueKey: "currencyID",
        optionKey: "currencyCode",
        getListUrl: "/api/v1/common/Currency"
      },
      {
        label: "Description",
        key: "description",
        type: "textArea",
        required: true,
        placeholder: "Description",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "Add-ons",
    hasClearButton: true,
    submitUrl: "/api/v1/product-addon",
  },

  "/settings/payment-gateways": {
    Category: "Payments",
    title: "Payment Gateway",
    formLabel: "",
    fields: [
      // {
      //   label: "Gateway Name",
      //   key: "providerName",
      //   type: "select",
      //   required: true,
      //   defaultList: [
      //     { value: "razorpay", option: "Razorpay" },
      //     { value: "phonepe", option: "PhonePe" },
      //     { value: "paytabs", option: "PayTabs" },
      //   ],
      //   valueKey: "value",
      //   optionKey: "option",
      // },
      {
        label: "Gateway Name",
        key: "providerName",
        type: "input",
        required: true,
        placeholder: "Gateway Name",
      },
      {
        label: "API Key",
        key: "apiKey",
        type: "input",
        required: true,
        placeholder: "API Key",
      },
      {
        label: "Secret Key",
        key: "secretKey",
        type: "input",
        required: true,
        placeholder: "Secret Key",
      },
      {
        label: "Endpoint Url",
        key: "endpointURL",
        type: "input",
        required: true,
        placeholder: "Endpoint Url",
      },
      {
        label: "Supported Modes",
        key: "supportedModes",
        type: "input",
        required: true,
        placeholder: "Supported Modes",
      },
      {
        label: "Status",
        key: "isActive",
        type: "select",
        required: true,
        placeholder: "Status",
        defaultList: [
          { value: true, option: "Active" },
          { value: false, option: "Invative" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "Payment Gateway",
    hasClearButton: true,
    submitUrl: "/api/v1/payment-gateway",
  },

  "/settings/currency": {
    Category: "Settings",
    title: "Currency",
    formLabel: "",
    fields: [
      {
       label: "Currency Code",
        key: "currencyCode",
        type: "input",
        required: true,
        placeholder: "Currrency Code",
      },
      {
        label: "Country Name",
        key: "countryName",
        type: "select",
        required: true,
        valueKey: "countryId",
        optionKey: "countryName",
        getListUrl: "/api/v1/common/countries",
      },
      {
        label: "Currency Symbol",
        key: "symbol",
        type: "input",
        required: true,
        placeholder: "Currency Symbol",
      },
      {
        label: "Decimal Places",
        key: "decimalPlaces",
        type: "number",
        required: true,
        placeholder: "Decimal Places",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "Currency",
    hasClearButton: true,
    submitUrl: "/api/v1/currency",
  },
  "/sales/leads/convert-to-deal": {
    Category: "Deals",
    title: "To Deals",
    formLabel: "",
    fields: [
      {
       label: "Currency Code",
        key: "currencyCode",
        type: "input",
        required: true,
        placeholder: "Currrency Code",
      },
      {
        label: "Country Name",
        key: "countryName",
        type: "select",
        required: true,
        valueKey: "countryId",
        optionKey: "countryName",
        getListUrl: "/api/v1/common/countries",
      },
      {
        label: "Currency Symbol",
        key: "symbol",
        type: "input",
        required: true,
        placeholder: "Currency Symbol",
      },
      {
        label: "Decimal Places",
        key: "decimalPlaces",
        type: "number",
        required: true,
        placeholder: "Decimal Places",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "To Deals",
    hasClearButton: true,
    submitUrl: "/api/v1/currency",
  },
  "/settings/servers": {
    Category: "Settings",
    title: "Server",
    formLabel: "",
    fields: [
      {
       label: "Server Name",
        key: "serverName",
        type: "input",
        required: true,
        placeholder: "Server Name",
      },
      {
        label: "Region",
        key: "region",
        type: "select",
        required: true,
        valueKey: "countryId",
        optionKey: "countryName",
        getListUrl: "/api/v1/common/countries",
      },
      {
        label: "IP Address",
        key: "ipAddress",
        type: "input",
        required: true,
        placeholder: "IP Address",
      },
      {
        label: "Status",
        key: "isActive",
        type: "select",
        required: true,
        placeholder: "Status",
        defaultList: [
          { value: true, option: "Active" },
          { value: false, option: "Invative" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Validity",
        key: "validity",
        type: "dateTime",
        required: true,
      },
      {
        label: "Database Limit",
        key: "databaseLimit",
        type: "number",
        required: true,
        placeholder: "Database Limit",
      },
      {
        label: "Remarks",
        key: "remarks",
        type: "input",
        required: true,
        placeholder: "Remarks",
      },
      {
        label: "Is Default",
        key: "isDefault",
        type: "checkbox",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "Server",
    hasClearButton: true,
    submitUrl: "/api/v1/server",
  },
};
