// import { FaUserCog } from 'react-icons/fa';

export const formFieldconfig = {
  "/users/role": {
    Category: "User & Role",
    title: "Role",
    formLabel: "Define access levels for user roles",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "Role Name",
        key: "typeName",
        type: "input",
        required: true,
        placeholder: "e.g., Admin, Super Admin",
      },
      {
        label: "Description",
        key: "description",
        type: "input",
        required: true,
        placeholder: "Description",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "Role",
    hasClearButton: true,
    submitUrl: "/api/v1/user-type",
  },

  "/users": {
    Category: "User & Role",
    title: "User",
    formLabel: "Define access levels for user",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "User Name",
        key: "userName",
        type: "input",
        required: true,
        placeholder: "Username",
      },
      {
        label: "Email",
        key: "userEmail",
        type: "input",
        required: true,
        placeholder: "Email",
      },
      {
        label: "Password",
        key: "passwordHash",
        type: "password",
        required: true,
        placeholder: "Password",
      },
      {
        label: "Role",
        key: "userTypeId",
        type: "select",
        required: true,
        placeholder: "Role",
        getListUrl: "/api/v1/user-type",
        valueKey: "userTypeId",
        optionKey: "typeName",
      },
      {
        label: "Status",
        key: "isActive",
        type: "select",
        required: true,
        placeholder: "Status",
        defaultList: [
          { value: true, option: "Active" },
          { value: false, option: "Invative" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Country",
        key: "countryID",
        type: "select",
        required: true,
        placeholder: "Country",
        valueKey: "countryId",
        optionKey: "countryName",
        getListUrl: "/api/v1/common/countries",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "User",
    hasClearButton: true,
    submitUrl: "/api/v1/user",
  },

  "/users/update": {
    Category: "User & Role",
    title: "User",
    formLabel: "Define access levels for user",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "User Name",
        key: "userName",
        type: "input",
        required: true,
        placeholder: "Username",
      },
      {
        label: "Email",
        key: "userEmail",
        type: "input",
        required: true,
        placeholder: "Email",
      },
      {
        label: "Role",
        key: "userTypeId",
        type: "select",
        required: true,
        placeholder: "Role",
        getListUrl: "/api/v1/user-type",
        valueKey: "userTypeId",
        optionKey: "typeName",
      },
      {
        label: "Status",
        key: "isActive",
        type: "select",
        required: true,
        placeholder: "Status",
        defaultList: [
          { value: true, option: "Active" },
          { value: false, option: "Invative" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Country",
        key: "countryID",
        type: "select",
        required: true,
        placeholder: "Country",
        valueKey: "countryId",
        optionKey: "countryName",
        getListUrl: "/api/v1/common/countries",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "User",
    hasClearButton: true,
    submitUrl: "/api/v1/user",
  },

  "/products": {
    Category: "Products",
    title: "Product",
    formLabel: "",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "Product Name",
        key: "name",
        type: "input",
        required: true,
        placeholder: "Product Name",
      },
      {
        label: "Product Type",
        key: "productTypeID",
        type: "select",
        required: true,
        defaultList: [
          { value: 1, option: "Licensed" },
          { value: 2, option: "Subscription" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Status",
        key: "isActive",
        type: "select",
        required: true,
        placeholder: "Status",
        defaultList: [
          { value: true, option: "Active" },
          { value: false, option: "Invative" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Description",
        key: "description",
        type: "textArea",
        required: true,
        placeholder: "Description",
        class: "w-32",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "Product",
    hasClearButton: true,
    submitUrl: "/api/v1/product",
  },
  "/products/plan": {
    Category: "Product Plans",
    title: "Plan",
    formLabel: "",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "Plan Name",
        key: "planName",
        type: "input",
        required: true,
        placeholder: "Plan Name",
      },
      {
        label: "Currency",
        key: "currencyID",
        type: "select",
        required: true,
        defaultList: [
          { value: "4c89c5a5-95cd-fefd-b1df-7b46a68c1d12", option: "SAR" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Plan Price",
        key: "planPrice",
        type: "number",
        required: true,
        placeholder: "Plan Price",
      },
      {
        label: "Billing Cycle",
        key: "billingCycle",
        type: "select",
        required: true,
        defaultList: [
          { value: "monthly", option: "Monthly" },
          { value: "quarterly", option: "Quarterly" },
          { value: "semi_annually", option: "Semi-Annually" },
          { value: "annually", option: "Annually" },
          { value: "biennially", option: "Biennially" },
          { value: "triennially", option: "Triennially" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
      {
        label: "Status",
        key: "isActive",
        type: "select",
        required: true,
        defaultList: [
          { value: true, option: "Active" },
          { value: false, option: "Inactive" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "Plan",
    hasClearButton: true,
    submitUrl: "/api/v1/product-plan",
  },

  "/products/version": {
    Category: "Product Version",
    title: "Version",
    formLabel: "",
    // icon: <FaUserCog className="text-blue-600 text-xl" />,
    fields: [
      {
        label: "Version Number",
        key: "versionNumber",
        type: "input",
        required: true,
        placeholder: "Version Number",
      },
      {
        label: "Release Date",
        key: "releaseDate",
        type: "dateTime",
        required: true,
      },
      {
        label: "Version Price",
        key: "basePrice",
        type: "number",
        required: true,
        placeholder: "Version Price",
      },
      {
        label: "Currency",
        key: "currencyID",
        type: "select",
        required: true,
        defaultList: [
          { value: "8358cf62-245a-33b9-dafa-e275cc1a5318", option: "SAR" },
        ],
        valueKey: "value",
        optionKey: "option",
      },
    ],
    hasSubmitButton: true,
    submitButtonLabel: "Version",
    hasClearButton: true,
    submitUrl: "/api/v1/product-version",
  },
};
