import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import LayoutWrapper from "@/components/layout/LayoutWrapper";
import { Toaster } from 'react-hot-toast'
import { PermissionsProvider } from "@/context/PermissionsContext";
import { PermissionGate } from "@/components/permissions/PermissionGate";

const geistSans = Inter({
  // variable: "--font-geist-sans",
  // subsets: ["latin"],
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});



export const metadata: Metadata = {
  title: "Polosys CRM",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased bg-white`}
      >
        <Toaster position="top-right" reverseOrder={false} />
         <PermissionsProvider>
          <PermissionGate>
         <LayoutWrapper>{children}</LayoutWrapper>
         </PermissionGate>
         </PermissionsProvider>
      </body>
    </html>
  );
}
