import type { Metadata } from "next";
import { Inter , Geist_Mono } from "next/font/google";
import "../globals.css";
import LayoutWrapper from "@/components/layout/LayoutWrapper";
import { Toaster } from 'react-hot-toast'

const geistSans = Inter({
  // variable: "--font-geist-sans",
  // subsets: ["latin"],
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});



export const metadata: Metadata = {
  title: "Polosys CRM",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased bg-white`}
      >
        <Toaster position="top-right" reverseOrder={false} />
         <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
